# Generated by Django 4.2.7 on 2023-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="description",
            new_name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="about",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.TextField(blank=True, null=True),
        ),
    ]
