# Generated by Django 4.2.7 on 2023-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_description_user_age_remove_user_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(default="male", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=255,
            ),
        ),
    ]
