# Generated by Django 4.2.7 on 2023-11-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_account", "0003_sentimentanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentimentanalysis",
            name="tv_show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_account.tvshow",
            ),
        ),
    ]
